# Generated by Django 3.1.3 on 2021-01-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='pd',
            new_name='products',
        ),
    ]
