# Generated by Django 3.1.3 on 2021-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210118_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
