# Generated by Django 3.1.3 on 2021-01-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20210118_1633'),
        ('authln', '0003_auto_20210121_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('on track', 'on track'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('custumer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authln.custumer')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products')),
            ],
        ),
    ]
