# Generated by Django 3.1.3 on 2021-01-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210118_1633'),
        ('orders', '0002_auto_20210121_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoping_customer', to='product.products')),
                ('products', models.ManyToManyField(blank=True, to='product.Products')),
            ],
        ),
    ]
